using LotteryGame.Shared.Services.Interfaces;

namespace LotteryGame.Shared.Services;

public class TicketService : ITicketService {
    public List<int> GetAllTicketsForGame(IEnumerable<Player> players) {
        //tickets are generated by repeating the player number for the number of tickets they have
        var tickets = players
            .SelectMany(x => Enumerable.Repeat(x.PlayerNumber, x.NumberOfTickets))
            .ToList();
        tickets.Shuffle();
        return tickets;
    }
}